-- 1. waitlist 테이블 생성
CREATE TABLE public.waitlist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    source TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- 2. RLS(Row Level Security) 활성화
ALTER TABLE public.waitlist ENABLE ROW LEVEL SECURITY;

-- 3. 익명 사용자(anon)의 INSERT(데이터 추가) 허용 정책
CREATE POLICY "Enable insert for anonymous users" 
ON public.waitlist 
FOR INSERT 
TO anon 
WITH CHECK (true);

-- 주의: SELECT 권한은 부여하지 않아서, 다른 사람의 이메일이나 정보를 조회할 수 없게 합니다.

-- 4. 전체 카운트 조회를 위한 RPC 함수 생성
-- RLS 정책과 상관없이 카운트만 반환할 수 있도록 SECURITY DEFINER로 설정합니다.
CREATE OR REPLACE FUNCTION get_waitlist_count()
RETURNS integer
LANGUAGE sql
SECURITY DEFINER
AS $$
  SELECT count(*)::integer FROM public.waitlist;
$$;
